// Code generated by MockGen. DO NOT EDIT.
// Source: databases.go
//
// Generated by this command:
//
//	mockgen -source=databases.go -destination=databases_mock.go -package repository
//

// Package repository is a generated GoMock package.
package repository

import (
	infrastructure "puuclocks/internal/infrastructure"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabases is a mock of Databases interface.
type MockDatabases struct {
	ctrl     *gomock.Controller
	recorder *MockDatabasesMockRecorder
}

// MockDatabasesMockRecorder is the mock recorder for MockDatabases.
type MockDatabasesMockRecorder struct {
	mock *MockDatabases
}

// NewMockDatabases creates a new mock instance.
func NewMockDatabases(ctrl *gomock.Controller) *MockDatabases {
	mock := &MockDatabases{ctrl: ctrl}
	mock.recorder = &MockDatabasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabases) EXPECT() *MockDatabasesMockRecorder {
	return m.recorder
}

// DB mocks base method.
func (m *MockDatabases) DB() infrastructure.MySQL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(infrastructure.MySQL)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockDatabasesMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockDatabases)(nil).DB))
}

// RedisDB mocks base method.
func (m *MockDatabases) RedisDB() Redis {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedisDB")
	ret0, _ := ret[0].(Redis)
	return ret0
}

// RedisDB indicates an expected call of RedisDB.
func (mr *MockDatabasesMockRecorder) RedisDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedisDB", reflect.TypeOf((*MockDatabases)(nil).RedisDB))
}
